# Generated by Django 3.1.7 on 2021-03-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asigned_to',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
